name: Mi acción compuesta
description: Ejecuta varios pasos comunes en un solo bloque
inputs:
  mensaje:
    description: Mensaje a mostrar
    required: true
runs:
  using: "composite"
  steps:
    - name: Mostrar saludo
      run: echo "Hola desde la acción compuesta"

    - name: Mostrar mensaje
      run: echo "${{ inputs.mensaje }}"
