# .github/workflows/enviar-correo.yml
name: Enviar correo de prueba

on:
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub

jobs:
  enviar-correo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Enviar correo usando el composite
        uses: ./.github/actions/composite_email
        with:
          subject: "Correo de prueba desde GitHub Actions"
          body: "Hola, este es un correo enviado automáticamente desde un workflow."
          destination_email: "fabianmontes@hotmail.com"
          smtp_user: "fermontessanchez@gmail.com"
          smtp_pass: ${{ secrets.SMTP }}
          smtp_host: "smtp.gmail.com"
          smtp_port: "587"

